# Generated by Django 2.0.3 on 2019-01-04 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalRating',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalrating_player_a', to='api.Profile')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalrating_player_b', to='api.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
