# Generated by Django 2.1.2 on 2019-01-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_goalrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duopartner',
            unique_together={('player_a', 'player_b')},
        ),
        migrations.AlterUniqueTogether(
            name='goalrating',
            unique_together={('player_a', 'player_b')},
        ),
        migrations.AlterUniqueTogether(
            name='laddrmatch',
            unique_together={('player_a', 'player_b')},
        ),
    ]
