# Generated by Django 2.0.3 on 2018-08-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_psychograph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychepreference',
            name='potential_match',
        ),
        migrations.AddField(
            model_name='psychepreference',
            name='psychograph',
            field=models.ForeignKey(default='9cbc9e2e-99cc-43c8-bb7f-6096ba32dfcc', on_delete=django.db.models.deletion.CASCADE, to='api.Psychograph'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psychepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
