# Generated by Django 2.1.2 on 2019-01-17 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190110_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalscores_player_a', to='api.Profile')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalscores_player_b', to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_scores',
            field=models.ManyToManyField(through='api.GoalScores', to='api.Profile'),
        ),
    ]
