# Generated by Django 2.0.3 on 2018-08-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180823_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychograph',
            name='calibrator',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
