# Generated by Django 2.1.2 on 2019-01-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190117_0233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goalscores',
            unique_together={('player_a', 'player_b')},
        ),
    ]
