# Generated by Django 2.0.3 on 2019-01-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190117_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goal_scores',
        ),
    ]
