# Generated by Django 2.0.3 on 2018-09-05 02:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180829_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_a_accept', models.BooleanField(default=False)),
                ('player_b_accept', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to='api.Profile')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to='api.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='psychograph',
            unique_together={('johnny_rank', 'timmy_rank', 'spike_rank')},
        ),
    ]
