# Generated by Django 2.0.3 on 2018-09-07 02:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180905_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endorsements',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsee', to='api.Profile')),
                ('endorsement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Endorsement')),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorser', to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='endorsements',
            field=models.ManyToManyField(through='api.Endorsements', to='api.Endorsement'),
        ),
        migrations.AlterUniqueTogether(
            name='endorsements',
            unique_together={('endorser', 'endorsee', 'endorsement')},
        ),
    ]
