# Generated by Django 2.0.3 on 2018-09-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180907_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='skill',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
