# Generated by Django 2.0.3 on 2018-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180907_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
