# Generated by Django 2.1.2 on 2018-11-11 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuoPartner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_a_feedback', models.TextField(default=None, max_length=500, null=True)),
                ('player_b_feedback', models.TextField(default=None, max_length=500, null=True)),
                ('player_a_rating', models.IntegerField(default=None, null=True)),
                ('player_b_rating', models.IntegerField(default=None, null=True)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_duopartner_player_a', to='api.Profile')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_duopartner_player_b', to='api.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='match',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 5, 23, 9, 37, 779231, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='match',
            name='player_a_accept_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_b_accept_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='primary_reason',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='secondary_reason',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='tertiary_reason',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_match_player_a', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_match_player_b', to='api.Profile'),
        ),
    ]
