# Generated by Django 2.1.2 on 2018-11-29 02:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181115_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPreference',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, choices=[('Bronze V', 'Bronze V'), ('Bronze IV', 'Bronze IV'), ('Bronze III', 'Bronze III'), ('Bronze II', 'Bronze II'), ('Bronze I', 'Bronze I'), ('Silver V', 'Silver V'), ('Silver IV', 'Silver IV'), ('Silver III', 'Silver III'), ('Silver II', 'Silver II'), ('Silver I', 'Silver I'), ('Gold V', 'Gold V'), ('Gold IV', 'Gold IV'), ('Gold III', 'Gold III'), ('Gold II', 'Gold II'), ('Gold I', 'Gold I'), ('Platinum V', 'Platinum V'), ('Platinum IV', 'Platinum IV '), ('Platinum III', 'Platinum III'), ('Platinum II', 'Platinum II'), ('Platinum I', 'Platinum I'), ('Diamond V', 'Diamond V'), ('Diamond IV', 'Diamond IV'), ('Diamond III', 'Diamond III'), ('Diamond II', 'Diamond II'), ('Diamond I', 'Diamond I'), ('Challenger', 'Challenger')], max_length=15, null=True)),
                ('rank_importance', models.IntegerField(default=0)),
                ('role', models.CharField(blank=True, choices=[('Bottom', 'Bottom'), ('Support', 'Support'), ('Jungle', 'Jungle'), ('Mid', 'Mid'), ('Top', 'Top')], max_length=15, null=True)),
                ('role_importance', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availability',
        ),
        migrations.AddField(
            model_name='availability',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='time_of_day',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='availabilities',
            field=models.ManyToManyField(to='api.Availability'),
        ),
        migrations.AlterField(
            model_name='laddrmatch',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 2, 32, 18, 396199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 2, 32, 18, 396199, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='matchingpreference',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
