# Generated by Django 2.1.2 on 2018-11-29 02:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181129_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='top_champions',
        ),
        migrations.AlterField(
            model_name='laddrmatch',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 2, 38, 59, 651193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 2, 38, 59, 651193, tzinfo=utc)),
        ),
    ]
