# Generated by Django 2.1.2 on 2018-11-29 02:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181129_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='laddrmatch',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 2, 43, 0, 782619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 2, 43, 0, 782619, tzinfo=utc)),
        ),
    ]
