# Generated by Django 2.1.2 on 2018-11-29 03:05

import api.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181129_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatch',
            name='expired',
        ),
        migrations.AddField(
            model_name='laddrmatch',
            name='expires_at',
            field=models.DateTimeField(default=api.utility.default_match_expire),
        ),
    ]
