# Generated by Django 2.1.2 on 2018-12-20 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181206_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingpreference',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
