# Generated by Django 2.1.2 on 2018-12-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181220_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='player',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='psychepreference',
            name='psychograph',
        ),
        migrations.RemoveField(
            model_name='psychepreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Psychograph',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availabilities',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='johnny_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='num_profiles_ranked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_johnny_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_spike_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_timmy_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='server',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='spike_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timezones',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timmy_rank',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='PsychePreference',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
